# -*- coding: utf-8 -*-
"""pix2struct_안되는이유.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr2FWQNAHmR050hdn3TlZhU1n5EFR7hX
"""

# 셀 1. GPU 확인
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if not torch.cuda.is_available():
    raise RuntimeError("GPU가 연결되어 있지 않습니다. Colab 런타임 유형을 GPU(T4 권장)로 변경하세요.")

device = torch.device("cuda")
gpu_name = torch.cuda.get_device_name(0)

print("Device:", device)
print("GPU:", gpu_name)

print("GPU 확인 완료. 유료 GPU이면 30 epoch 실험에 더 적합합니다.")

from google.colab import drive
drive.mount('/content/drive')

# 셀 2. 패키지 설치
!pip install -q transformers accelerate sentencepiece pillow tqdm gdown pandas

# 셀 3. 기본 설정
import os
import re
import json
import math
import random
import tarfile
import zipfile
import shutil
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image, ImageEnhance, ImageFilter, ImageOps
from tqdm.auto import tqdm
import pandas as pd

from transformers import (
    Pix2StructProcessor,
    Pix2StructForConditionalGeneration,
    get_cosine_schedule_with_warmup,
)

SEED = 42
random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

MODEL_NAME = "google/pix2struct-base"
PROMPT = "이 식품 패키지 이미지에서 원재료명을 추출하세요."

MAX_SAMPLES = 3000
TRAIN_RATIO = 0.8

EPOCHS = 30
BATCH_SIZE = 1
ACCUMULATION_STEPS = 4
LEARNING_RATE = 3e-5
GRAD_CLIP_NORM = 1.0

EARLY_STOPPING_PATIENCE = 4
MIN_DELTA = 1e-4

MAX_PATCHES = 512
MAX_TARGET_LENGTH = 256
MAX_GENERATION_LENGTH = 256
EVAL_NUM_BEAMS_LIST = [1, 3]

# 이미지 전처리 옵션
USE_IMAGE_PREPROCESSING = True
USE_TRAIN_AUGMENTATION = False
RESIZE_LONG_SIDE = 1024
CONTRAST_FACTOR = 1.20
SHARPNESS_FACTOR = 1.10
DENOISE_SIZE = 3

ALLERGY_KEYWORDS = [
    "밀", "우유", "대두", "땅콩", "메밀", "고등어", "게", "새우",
    "돼지고기", "복숭아", "토마토", "호두", "알류", "계란", "난황", "난백",
    "아황산", "이산화황", "조개류", "굴", "전복", "홍합", "오징어"
]


TAR_ID = "1yt9MAel2hGzf9EwxXASzSpLjFnPIxJ7X"
LABEL_ID = "1WPKwrRuY5SHoj2ImpUYVshPbXdMpdBC8"

WORK_DIR = Path("/content/pix2struct_food_v2")
DOWNLOAD_DIR = WORK_DIR / "download"
DATA_DIR = WORK_DIR / "data"
IMAGE_DIR = DATA_DIR / "solo"
OUTPUT_DIR = Path("/content/drive/MyDrive/pix2struct_food_v2_result")

TAR_PATH = DOWNLOAD_DIR / "solo.tar"
LABEL_PATH = DOWNLOAD_DIR / "label_log.txt"

BEST_MODEL_DIR = OUTPUT_DIR / "pix2struct_v2_best"
FINAL_MODEL_DIR = OUTPUT_DIR / "pix2struct_v2_final"

WORK_DIR.mkdir(parents=True, exist_ok=True)
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("MODEL_NAME:", MODEL_NAME)
print("PROMPT:", PROMPT)
print("MAX_SAMPLES:", MAX_SAMPLES)
print("OUTPUT_DIR:", OUTPUT_DIR)

# 셀 4. solo.tar, label_log.txt 직접 다운로드
import gdown

if not TAR_PATH.exists():
    print("solo.tar 다운로드 시작")
    gdown.download(id=TAR_ID, output=str(TAR_PATH), quiet=False)
else:
    print("solo.tar already exists:", TAR_PATH)

if not LABEL_PATH.exists():
    print("label_log.txt 다운로드 시작")
    gdown.download(id=LABEL_ID, output=str(LABEL_PATH), quiet=False)
else:
    print("label_log.txt already exists:", LABEL_PATH)

if not TAR_PATH.exists():
    raise FileNotFoundError("solo.tar 다운로드 실패")
if not LABEL_PATH.exists():
    raise FileNotFoundError("label_log.txt 다운로드 실패")

print("TAR_PATH:", TAR_PATH, TAR_PATH.stat().st_size)
print("LABEL_PATH:", LABEL_PATH, LABEL_PATH.stat().st_size)

# 셀 5. solo.tar 압축 해제 및 이미지 확인
if IMAGE_DIR.exists():
    shutil.rmtree(IMAGE_DIR)
IMAGE_DIR.mkdir(parents=True, exist_ok=True)

print("압축 해제 시작:", TAR_PATH)

if str(TAR_PATH).endswith(".tar"):
    with tarfile.open(TAR_PATH, "r") as tar:
        tar.extractall(IMAGE_DIR)
elif str(TAR_PATH).endswith(".zip"):
    with zipfile.ZipFile(TAR_PATH, "r") as zip_ref:
        zip_ref.extractall(IMAGE_DIR)
else:
    raise ValueError("지원하지 않는 압축 형식입니다. tar 또는 zip만 지원합니다.")

image_extensions = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
image_paths = [path for path in IMAGE_DIR.rglob("*") if path.suffix.lower() in image_extensions]
image_paths = sorted(image_paths, key=lambda p: p.name)

print("Image count:", len(image_paths))
if len(image_paths) == 0:
    raise RuntimeError("solo.tar 안에서 이미지 파일을 찾지 못했습니다.")

print("이미지 예시:")
for path in image_paths[:10]:
    print(path.name, "|", path)

# 셀 6. label_log.txt 라벨 읽기
def clean_ingredient_text(text):
    text = text.strip()
    text = re.sub(r"^Ingredients\s*:\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^Ingredient\s*:\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^원재료명\s*:\s*", "", text)
    text = re.sub(r"^성분\s*:\s*", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def parse_label_line(line):
    line = line.strip()
    if not line:
        return None

    image_pattern = r"([^\s]+\.(?:png|jpg|jpeg|bmp|webp))"
    image_match = re.search(image_pattern, line, flags=re.IGNORECASE)
    if image_match:
        filename = Path(image_match.group(1)).name
        remaining_text = line[image_match.end():].strip()
        return {"filename": filename, "text": clean_ingredient_text(remaining_text), "raw": line}

    return {"filename": None, "text": clean_ingredient_text(line), "raw": line}

with open(LABEL_PATH, "r", encoding="utf-8") as f:
    raw_label_lines = f.readlines()

parsed_labels = []
for line in raw_label_lines:
    parsed = parse_label_line(line)
    if parsed is not None and parsed["text"]:
        parsed_labels.append(parsed)

filename_label_count = sum(1 for item in parsed_labels if item["filename"] is not None)
no_filename_label_count = sum(1 for item in parsed_labels if item["filename"] is None)

print("Label count:", len(parsed_labels))
print("Labels with filename:", filename_label_count)
print("Labels without filename:", no_filename_label_count)
if len(parsed_labels) == 0:
    raise RuntimeError("유효한 라벨을 찾지 못했습니다.")

print("라벨 예시:")
for item in parsed_labels[:5]:
    print(item)

# 셀 7. 이미지-라벨 매칭
image_by_name = {path.name: path for path in image_paths}
samples = []

if filename_label_count > 0:
    print("파일명 기준으로 이미지와 라벨을 매칭합니다.")
    missing_images = []
    for item in parsed_labels:
        filename = item["filename"]
        if filename is None:
            continue
        if filename in image_by_name:
            samples.append({"image_path": image_by_name[filename], "target_text": item["text"], "filename": filename})
        else:
            missing_images.append(filename)
    print("Matched sample count:", len(samples))
    print("Missing image count:", len(missing_images))
else:
    print("라벨에 파일명이 없으므로 이미지 정렬 순서와 라벨 줄 순서로 매칭합니다.")
    pair_count = min(len(image_paths), len(parsed_labels))
    if len(image_paths) != len(parsed_labels):
        print("[경고] 이미지 수와 라벨 수가 다릅니다.")
        print("Image count:", len(image_paths))
        print("Label count:", len(parsed_labels))
        print("매칭 가능한 개수만 사용:", pair_count)
    for image_path, item in zip(image_paths[:pair_count], parsed_labels[:pair_count]):
        samples.append({"image_path": image_path, "target_text": item["text"], "filename": image_path.name})

print("Final matched sample count:", len(samples))
if len(samples) == 0:
    raise RuntimeError("최종 매칭 샘플이 0개입니다.")

print("매칭 예시:")
for sample in samples[:5]:
    print(sample["filename"], "=>", sample["target_text"][:120])

# 셀 8. 3000개 사용 및 Train/Val 분할
random.seed(SEED)
random.shuffle(samples)

if len(samples) >= MAX_SAMPLES:
    samples = samples[:MAX_SAMPLES]
    print(f"사용 가능한 데이터가 {MAX_SAMPLES}개 이상이므로 셔플 후 {MAX_SAMPLES}개만 사용합니다.")
else:
    print(f"[경고] 사용 가능한 데이터가 {MAX_SAMPLES}개 미만입니다. 현재 데이터 전체를 사용합니다.")

split_index = int(len(samples) * TRAIN_RATIO)
if split_index <= 0 or split_index >= len(samples):
    raise RuntimeError("데이터가 너무 적어 train/val 분할이 불가능합니다.")

train_samples = samples[:split_index]
val_samples = samples[split_index:]

print("Total used:", len(samples))
print("Train count:", len(train_samples))
print("Val count:", len(val_samples))
print("Train ratio:", len(train_samples) / len(samples))
print("Val ratio:", len(val_samples) / len(samples))

# 셀 9. 이미지 전처리 함수와 Dataset 정의
def resize_long_side(image, long_side=1024):
    width, height = image.size
    current_long_side = max(width, height)
    if current_long_side <= long_side:
        return image
    scale = long_side / current_long_side
    new_size = (int(width * scale), int(height * scale))
    return image.resize(new_size, Image.Resampling.LANCZOS)

def preprocess_image(image, train=False):
    image = ImageOps.exif_transpose(image).convert("RGB")

    if USE_IMAGE_PREPROCESSING:
        # 1) Resize: 너무 큰 이미지를 줄여 학습/추론 안정화
        image = resize_long_side(image, RESIZE_LONG_SIDE)

        # 2) Contrast: 흐린 글자 대비 강화
        image = ImageEnhance.Contrast(image).enhance(CONTRAST_FACTOR)

        # 3) Denoise: 작은 노이즈 완화
        image = image.filter(ImageFilter.MedianFilter(size=DENOISE_SIZE))

        # 4) Sharpen: 글자 경계 조금 강화
        image = ImageEnhance.Sharpness(image).enhance(SHARPNESS_FACTOR)

    if train and USE_TRAIN_AUGMENTATION:
        # 선택적 약한 증강. 과하면 OCR이 망가질 수 있어서 매우 약하게만 적용.
        if random.random() < 0.3:
            image = ImageEnhance.Brightness(image).enhance(random.uniform(0.9, 1.1))
        if random.random() < 0.3:
            image = ImageEnhance.Contrast(image).enhance(random.uniform(0.9, 1.15))
        if random.random() < 0.2:
            image = image.rotate(random.uniform(-1.5, 1.5), expand=True, fillcolor=(255, 255, 255))

    return image

class FoodIngredientDataset(Dataset):
    def __init__(self, samples, train=False):
        self.samples = samples
        self.train = train

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        sample = self.samples[index]
        image = Image.open(sample["image_path"]).convert("RGB")
        image = preprocess_image(image, train=self.train)
        return {
            "image": image,
            "target_text": sample["target_text"],
            "filename": sample["filename"],
        }

train_dataset = FoodIngredientDataset(train_samples, train=True)
val_dataset = FoodIngredientDataset(val_samples, train=False)

print("Train dataset:", len(train_dataset))
print("Val dataset:", len(val_dataset))
print("USE_IMAGE_PREPROCESSING:", USE_IMAGE_PREPROCESSING)
print("USE_TRAIN_AUGMENTATION:", USE_TRAIN_AUGMENTATION)

# 셀 10. Processor와 Model 로드
processor = Pix2StructProcessor.from_pretrained(MODEL_NAME)
processor.image_processor.is_vqa = False

model = Pix2StructForConditionalGeneration.from_pretrained(MODEL_NAME)
model.to(device)

print("Model loaded:", MODEL_NAME)
print("processor.image_processor.is_vqa:", processor.image_processor.is_vqa)
print("Device:", next(model.parameters()).device)

# 셀 11. Collate 함수 정의
def collate_fn(batch):
    images = [item["image"] for item in batch]
    target_texts = [item["target_text"] for item in batch]
    prompts = [PROMPT for _ in batch]

    encoding = processor(
        images=images,
        text=prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_patches=MAX_PATCHES,
    )

    labels = processor.tokenizer(
        target_texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_TARGET_LENGTH,
    ).input_ids

    labels[labels == processor.tokenizer.pad_token_id] = -100
    encoding["labels"] = labels
    encoding["target_texts"] = target_texts
    encoding["filenames"] = [item["filename"] for item in batch]
    return encoding

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn, num_workers=0)

print("Train loader batches:", len(train_loader))
print("Val loader batches:", len(val_loader))

# 셀 12. Smoke Batch 확인
smoke_batch = next(iter(train_loader))

print("Smoke batch keys:", smoke_batch.keys())
print("flattened_patches shape:", smoke_batch["flattened_patches"].shape)
print("attention_mask shape:", smoke_batch["attention_mask"].shape)
print("labels shape:", smoke_batch["labels"].shape)
print("target example:", smoke_batch["target_texts"][0])

model.train()
smoke_inputs = {
    "flattened_patches": smoke_batch["flattened_patches"].to(device),
    "attention_mask": smoke_batch["attention_mask"].to(device),
    "labels": smoke_batch["labels"].to(device),
}

with torch.cuda.amp.autocast(dtype=torch.float16):
    smoke_outputs = model(**smoke_inputs)
    smoke_loss = smoke_outputs.loss

print("Smoke loss:", float(smoke_loss.detach().cpu()))

# 셀 13. Optimizer와 Scheduler 설정
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)

num_update_steps_per_epoch = math.ceil(len(train_loader) / ACCUMULATION_STEPS)
total_training_steps = EPOCHS * num_update_steps_per_epoch
warmup_steps = max(1, int(total_training_steps * 0.1))

scheduler = get_cosine_schedule_with_warmup(
    optimizer=optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_training_steps,
)

scaler = torch.cuda.amp.GradScaler()

print("EPOCHS:", EPOCHS)
print("EARLY_STOPPING_PATIENCE:", EARLY_STOPPING_PATIENCE)
print("BATCH_SIZE:", BATCH_SIZE)
print("ACCUMULATION_STEPS:", ACCUMULATION_STEPS)
print("Learning rate:", LEARNING_RATE)
print("Total training steps:", total_training_steps)
print("Warmup steps:", warmup_steps)

# 셀 14. 학습 진행
import json

CHECKPOINT_INFO_PATH = OUTPUT_DIR / "resume_info.json"
history_csv_path = OUTPUT_DIR / "train_history.csv"

start_epoch = 0
best_val_loss = float("inf")
patience_counter = 0
train_history = []

if BEST_MODEL_DIR.exists() and (BEST_MODEL_DIR / "config.json").exists() and CHECKPOINT_INFO_PATH.exists():
    print("=" * 60)
    print("🔄 구글 드라이브에서 기존 학습 가중치를 발견했습니다! 이어서 학습을 시작합니다.")

    # 1. 중간 저장된 가중치로 모델 교체 복구
    model = Pix2StructForConditionalGeneration.from_pretrained(BEST_MODEL_DIR)
    model.to(device)

    # 2. 이어할 에폭, 최고 loss, patience 정보 복구
    with open(CHECKPOINT_INFO_PATH, "r", encoding="utf-8") as f:
        checkpoint_info = json.load(f)
    start_epoch = checkpoint_info["epoch"]  # 저장 당시 완료된 에폭
    best_val_loss = checkpoint_info["best_val_loss"]
    patience_counter = checkpoint_info["patience_counter"]

    # 3. 기존 Loss 기록(History) 복구
    if history_csv_path.exists():
        train_history = pd.read_csv(history_csv_path).to_dict(orient="records")

    # 4. 스케줄러 강제 매칭 (지나간 스텝만큼 스케줄러를 당겨줍니다)
    # 1에폭당 업데이트 스텝 수 계산
    num_update_steps_per_epoch = math.ceil(len(train_loader) / ACCUMULATION_STEPS)
    passed_steps = start_epoch * num_update_steps_per_epoch
    for _ in range(passed_steps):
        scheduler.step()

    print(f"▶️ [복구 완료] Epoch {start_epoch + 1}부터 재시작합니다. (기존 최고 Val Loss: {best_val_loss:.6f})")
    print("=" * 60)
else:
    print("🆕 기존 학습 기록이 없으므로 처음(Epoch 1)부터 새롭게 학습을 시작합니다.")

# -------------------------------------------------------------------

model.train()
global_step = start_epoch * math.ceil(len(train_loader) / ACCUMULATION_STEPS) if 'start_epoch' in locals() else 0

for epoch in range(start_epoch, EPOCHS):
    print("=" * 60)
    print(f"Epoch {epoch + 1}/{EPOCHS}")
    print("=" * 60)

    running_loss = 0.0
    optimizer.zero_grad(set_to_none=True)
    progress_bar = tqdm(train_loader, desc=f"Training epoch {epoch + 1}")

    for step, batch in enumerate(progress_bar):
        inputs = {
            "flattened_patches": batch["flattened_patches"].to(device),
            "attention_mask": batch["attention_mask"].to(device),
            "labels": batch["labels"].to(device),
        }

        with torch.cuda.amp.autocast(dtype=torch.float16):
            outputs = model(**inputs)
            loss = outputs.loss
            loss_for_backward = loss / ACCUMULATION_STEPS

        scaler.scale(loss_for_backward).backward()
        running_loss += float(loss.detach().cpu())

        should_update = (step + 1) % ACCUMULATION_STEPS == 0
        is_last_step = (step + 1) == len(train_loader)
        if should_update or is_last_step:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad(set_to_none=True)
            global_step += 1

        avg_loss = running_loss / (step + 1)
        progress_bar.set_postfix({"loss": f"{avg_loss:.4f}", "lr": scheduler.get_last_lr()[0]})

        if step == 0:
            print("First batch loss:", float(loss.detach().cpu()))

    epoch_avg_train_loss = running_loss / len(train_loader)
    epoch_avg_val_loss = compute_validation_loss(model, val_loader)

    history_row = {
        "epoch": epoch + 1,
        "train_loss": epoch_avg_train_loss,
        "val_loss": epoch_avg_val_loss,
        "lr": scheduler.get_last_lr()[0],
    }
    train_history.append(history_row)

    print(f"Epoch {epoch + 1} train loss: {epoch_avg_train_loss:.6f}")
    print(f"Epoch {epoch + 1} val loss  : {epoch_avg_val_loss:.6f}")

    # Early Stopping 및 저장 판단
    improved = epoch_avg_val_loss < (best_val_loss - MIN_DELTA)

    if improved:
        best_val_loss = epoch_avg_val_loss
        patience_counter = 0

        # 가중치 구글 드라이브에 실시간 저장
        BEST_MODEL_DIR.mkdir(parents=True, exist_ok=True)
        model.save_pretrained(BEST_MODEL_DIR)
        processor.save_pretrained(BEST_MODEL_DIR)
        print(f"✅ Best model updated. best_val_loss={best_val_loss:.6f}")
    else:
        patience_counter += 1
        print(f"⚠️ Validation loss 개선 없음. patience {patience_counter}/{EARLY_STOPPING_PATIENCE}")

    # [핵심] 개선 여부와 상관없이, 이번 에폭이 끝난 시점의 메타 정보를 항상 구글 드라이브에 백업 (튕겼을 때 이어하기용)
    checkpoint_meta = {
        "epoch": epoch + 1,
        "best_val_loss": best_val_loss,
        "patience_counter": patience_counter
    }
    with open(CHECKPOINT_INFO_PATH, "w", encoding="utf-8") as f:
        json.dump(checkpoint_meta, f, indent=4)

    # 실시간 History CSV 저장
    pd.DataFrame(train_history).to_csv(history_csv_path, index=False)

    if patience_counter >= EARLY_STOPPING_PATIENCE:
        print("🛑 EarlyStopping 발동: 과적합 방지를 위해 학습을 중단합니다.")
        break

# 최종 완료 저장
print("\n" + "="*60)
print("💾 최종 모델 및 학습 로그 저장 중...")
print("="*60)

FINAL_MODEL_DIR.mkdir(parents=True, exist_ok=True)
model.save_pretrained(FINAL_MODEL_DIR)
processor.save_pretrained(FINAL_MODEL_DIR)
print(f"✅ Final model saved to: {FINAL_MODEL_DIR}")

history_df = pd.DataFrame(train_history)
print(f"✅ Train history saved to: {history_csv_path}")
print("📊 학습 로그 요약:")
print(history_df.to_string(index=False))

# 셀 15. 평가 함수 정의 + 출력 후처리
def normalize_text(text):
    text = text or ""
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    text = text.replace(" ,", ",")
    text = text.replace(", ", ", ")
    return text.strip()

def clean_generated_text(text):
    """선배 피드백 반영: <s>, </s>, <pad> 같은 특수 토큰 제거"""
    text = text or ""
    special_tokens = [
        "<s>", "</s>", "<pad>", "<unk>",
        processor.tokenizer.pad_token if processor.tokenizer.pad_token else "",
        processor.tokenizer.eos_token if processor.tokenizer.eos_token else "",
        processor.tokenizer.bos_token if processor.tokenizer.bos_token else "",
    ]
    for token in special_tokens:
        if token:
            text = text.replace(token, "")
    text = clean_ingredient_text(text)
    text = normalize_text(text)
    return text

def levenshtein_distance(a, b):
    a = a or ""
    b = b or ""
    previous_row = list(range(len(b) + 1))
    for i, char_a in enumerate(a, start=1):
        current_row = [i]
        for j, char_b in enumerate(b, start=1):
            insert_cost = current_row[j - 1] + 1
            delete_cost = previous_row[j] + 1
            replace_cost = previous_row[j - 1] + (0 if char_a == char_b else 1)
            current_row.append(min(insert_cost, delete_cost, replace_cost))
        previous_row = current_row
    return previous_row[-1]

def calculate_sample_cer(prediction, reference):
    reference = reference or ""
    if len(reference) == 0:
        return 0.0
    return levenshtein_distance(prediction, reference) / len(reference)

def calculate_cer(predictions, references):
    total_distance = 0
    total_chars = 0
    for pred, ref in zip(predictions, references):
        total_distance += levenshtein_distance(pred, ref)
        total_chars += len(ref)
    return total_distance / total_chars if total_chars > 0 else 0.0

def extract_allergy_keywords(text):
    return {keyword for keyword in ALLERGY_KEYWORDS if keyword in text}

def calculate_allergy_metrics(predictions, references):
    true_positive = 0
    false_positive = 0
    false_negative = 0
    for pred, ref in zip(predictions, references):
        pred_set = extract_allergy_keywords(pred)
        ref_set = extract_allergy_keywords(ref)
        true_positive += len(pred_set & ref_set)
        false_positive += len(pred_set - ref_set)
        false_negative += len(ref_set - pred_set)

    precision = true_positive / (true_positive + false_positive) if (true_positive + false_positive) > 0 else 0.0
    recall = true_positive / (true_positive + false_negative) if (true_positive + false_negative) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    return {
        "allergy_precision": precision,
        "allergy_recall": recall,
        "allergy_f1": f1,
        "true_positive": true_positive,
        "false_positive": false_positive,
        "false_negative": false_negative,
    }

def classify_error_type(prediction, reference):
    pred_allergy = extract_allergy_keywords(prediction)
    ref_allergy = extract_allergy_keywords(reference)

    if not prediction.strip():
        return "empty_prediction"
    if any("\u4e00" <= ch <= "\u9fff" for ch in prediction):
        return "chinese_or_hanja_token"
    if len(prediction) < max(5, len(reference) * 0.4):
        return "too_short_or_missing_text"
    if len(prediction) > len(reference) * 1.8:
        return "too_long_or_hallucination"
    if ref_allergy - pred_allergy:
        return "allergy_keyword_missing"
    if pred_allergy - ref_allergy:
        return "allergy_keyword_false_positive"
    return "general_ocr_error"

print("Evaluation functions ready.")

# 셀 16. 모델 평가
if BEST_MODEL_DIR.exists():
    print("Best model을 로드해서 평가합니다:", BEST_MODEL_DIR)
    model = Pix2StructForConditionalGeneration.from_pretrained(BEST_MODEL_DIR).to(device)
else:
    print("[경고] Best model dir이 없어 현재 메모리의 model로 평가합니다.")

model.eval()
all_eval_results = {}

for num_beams in EVAL_NUM_BEAMS_LIST:
    print("=" * 60)
    print(f"Evaluating with num_beams = {num_beams}")
    print("=" * 60)

    predictions = []
    references = []
    filenames = []
    sample_cers = []
    error_types = []

    with torch.no_grad():
        for batch in tqdm(val_loader, desc=f"Evaluating beam={num_beams}"):
            generation_inputs = {
                "flattened_patches": batch["flattened_patches"].to(device),
                "attention_mask": batch["attention_mask"].to(device),
            }
            generated_ids = model.generate(
                **generation_inputs,
                max_new_tokens=MAX_GENERATION_LENGTH,
                num_beams=num_beams,
            )

            decoded_predictions = processor.batch_decode(generated_ids, skip_special_tokens=False)

            for pred, ref, filename in zip(decoded_predictions, batch["target_texts"], batch["filenames"]):
                clean_pred = clean_generated_text(pred)
                clean_ref = normalize_text(ref)

                predictions.append(clean_pred)
                references.append(clean_ref)
                filenames.append(filename)
                sample_cers.append(calculate_sample_cer(clean_pred, clean_ref))
                error_types.append(classify_error_type(clean_pred, clean_ref))

    cer = calculate_cer(predictions, references)
    allergy_metrics = calculate_allergy_metrics(predictions, references)

    all_eval_results[num_beams] = {
        "num_beams": num_beams,
        "predictions": predictions,
        "references": references,
        "filenames": filenames,
        "sample_cers": sample_cers,
        "error_types": error_types,
        "cer": cer,
        "allergy_metrics": allergy_metrics,
    }

    print("=" * 60)
    print(f"Evaluation Results - beam={num_beams}")
    print("=" * 60)
    print("CER:", cer)
    print("Allergy Keyword Precision:", allergy_metrics["allergy_precision"])
    print("Allergy Keyword Recall:", allergy_metrics["allergy_recall"])
    print("Allergy Keyword F1:", allergy_metrics["allergy_f1"])
    print("TP:", allergy_metrics["true_positive"])
    print("FP:", allergy_metrics["false_positive"])
    print("FN:", allergy_metrics["false_negative"])

    error_df = pd.DataFrame({"error_type": error_types})
    print("\nError type count:")
    print(error_df["error_type"].value_counts())

    print("\n예측 샘플:")
    for i in range(min(5, len(predictions))):
        print("-" * 60)
        print("File:", filenames[i])
        print("CER :", sample_cers[i])
        print("ERR :", error_types[i])
        print("REF :", references[i])
        print("PRED:", predictions[i])

print("Beam 1, Beam 3 평가 완료")

#수정파라미터로 베스트모델로 돌려봤을 때

import pandas as pd
import torch
from tqdm import tqdm


if BEST_MODEL_DIR.exists():
    print("수정한 파라미터로 Best model을 다시 로드", BEST_MODEL_DIR)
    model = Pix2StructForConditionalGeneration.from_pretrained(BEST_MODEL_DIR).to(device)
else:
    print("경로가 없")

model.eval()
all_eval_results = {}

FAST_EVAL_BEAMS = [1]

for num_beams in FAST_EVAL_BEAMS:
    print("=" * 60)
    print(f"Evaluating with num_beams = {num_beams}")
    print("=" * 60)

    predictions = []
    references = []
    filenames = []
    sample_cers = []
    error_types = []

    with torch.no_grad():
        for batch in tqdm(val_loader, desc=f"Evaluating beam={num_beams}"):
            generation_inputs = {
                "flattened_patches": batch["flattened_patches"].to(device),
                "attention_mask": batch["attention_mask"].to(device),
            }


            generated_ids = model.generate(
                **generation_inputs,
                max_new_tokens=MAX_GENERATION_LENGTH,
                num_beams=num_beams,
                repetition_penalty=2.5,          # 똑같은 단어 반복 시 패널티 부여 (뇌절 차단)
                no_repeat_ngram_size=3,          # 3글자 이상 연속 중복 절대 금지
                early_stopping=True              # 문장이 끝나면 즉시 연산 종료 (속도 획기적 단축)
            )

            decoded_predictions = processor.batch_decode(generated_ids, skip_special_tokens=True)

            for pred, ref, filename in zip(decoded_predictions, batch["target_texts"], batch["filenames"]):
                # 깨끗해진 텍스트를 공백만 제거하여 바인딩
                clean_pred = pred.strip()
                clean_ref = normalize_text(ref)  # 기존 공통 함수 유지

                predictions.append(clean_pred)
                references.append(clean_ref)
                filenames.append(filename)

                # 지표 계산 및 에러 타입 분류 (기존 함수 활용)
                sample_cers.append(calculate_sample_cer(clean_pred, clean_ref))
                error_types.append(classify_error_type(clean_pred, clean_ref))

    # 최종 스코어 산출
    cer = calculate_cer(predictions, references)
    allergy_metrics = calculate_allergy_metrics(predictions, references)

    all_eval_results[num_beams] = {
        "num_beams": num_beams,
        "predictions": predictions,
        "references": references,
        "filenames": filenames,
        "sample_cers": sample_cers,
        "error_types": error_types,
        "cer": cer,
        "allergy_metrics": allergy_metrics,
    }

    print("=" * 60)
    print(f"📊 [개선 완료] Evaluation Results - beam={num_beams}")
    print("=" * 60)
    print("CER (글자 에러율):", cer)
    print("Allergy Keyword Precision (정밀도):", allergy_metrics["allergy_precision"])
    print("Allergy Keyword Recall (재현율):", allergy_metrics["allergy_recall"])
    print("Allergy Keyword F1 (종합 점수):", allergy_metrics["allergy_f1"])
    print(f"정답 매칭 수 (TP): {allergy_metrics['true_positive']} | 오답 수 (FP): {allergy_metrics['false_positive']}")

    error_df = pd.DataFrame({"error_type": error_types})
    print("\n에러 유형 분포:")
    print(error_df["error_type"].value_counts())

    print("\n👀 실제 예측결과 샘플 확인:")
    for i in range(min(5, len(predictions))):
        print("-" * 60)
        print("File:", filenames[i])
        print("CER :", sample_cers[i])
        print("ERR :", error_types[i])
        print("REF (진짜정답):", references[i])
        print("PRED(개선된AI):", predictions[i])

print("\n완료되었습니다!")

#블랙이미지를 주고 테스트. 같은 값들이 계속 나오는것에 대한 의문
import torch

model.eval()
with torch.no_grad():
    # 1. val_loader에서 딱 첫 번째 배치 하나만 가져옵니다.
    for batch in val_loader:
        # 2. 이미지 입력(flattened_patches)을 전부 0(완전 까만 화면)으로 강제 초기화.
        black_patches = torch.zeros_like(batch["flattened_patches"]).to(device)
        attention_mask = batch["attention_mask"].to(device)

        # 3. 까만 화면을 주고 예측
        generated_ids = model.generate(
            flattened_patches=black_patches,
            attention_mask=attention_mask,
            max_new_tokens=MAX_GENERATION_LENGTH,
            num_beams=1,
            repetition_penalty=2.5,
            no_repeat_ngram_size=3,
            early_stopping=True
        )

        decoded_predictions = processor.batch_decode(generated_ids, skip_special_tokens=True)

        print("=" * 60)
        print("완전 까만 화면을 줬을 때 AI의 반응")
        print("=" * 60)
        for i, pred in enumerate(decoded_predictions[:3]):
            print(f"Sample {i+1} PRED: {pred.strip()}")
        break # 첫 배치만 보고 종료

# 순정 모델 테스트 결과
from transformers import Pix2StructForConditionalGeneration

print("🔄 학습 전 순정 원본 Pix2Struct 모델을 로드합니다...")
raw_model = Pix2StructForConditionalGeneration.from_pretrained("google/pix2struct-base").to(device)
raw_model.eval()

with torch.no_grad():
    for batch in val_loader:
        generation_inputs = {
            "flattened_patches": batch["flattened_patches"].to(device),
            "attention_mask": batch["attention_mask"].to(device),
        }

        generated_ids = raw_model.generate(
            **generation_inputs,
            max_new_tokens=MAX_GENERATION_LENGTH,
            num_beams=1,
            repetition_penalty=2.5,
            no_repeat_ngram_size=3,
            early_stopping=True
        )

        decoded_predictions = processor.batch_decode(generated_ids, skip_special_tokens=True)

        print("=" * 60)
        print("🍏 [순정 모델 결과] 학습 전 원본 모델의 반응")
        print("=" * 60)
        for i, (pred, ref) in enumerate(zip(decoded_predictions[:3], batch["target_texts"][:3])):
            print(f"Sample {i+1} REF : {ref.strip()[:30]}...")
            print(f"Sample {i+1} PRED: {pred.strip()}")
        break

# 셀 17. 최종 모델과 결과 저장
FINAL_MODEL_DIR.mkdir(parents=True, exist_ok=True)

model.save_pretrained(FINAL_MODEL_DIR)
processor.save_pretrained(FINAL_MODEL_DIR)

for num_beams, eval_result in all_eval_results.items():
    predictions = eval_result["predictions"]
    references = eval_result["references"]
    filenames = eval_result["filenames"]
    sample_cers = eval_result["sample_cers"]
    error_types = eval_result["error_types"]
    cer = eval_result["cer"]
    allergy_metrics = eval_result["allergy_metrics"]

    result_json_path = OUTPUT_DIR / f"pix2struct_v2_eval_results_beam{num_beams}.json"
    prediction_jsonl_path = OUTPUT_DIR / f"pix2struct_v2_predictions_beam{num_beams}.jsonl"
    prediction_csv_path = OUTPUT_DIR / f"pix2struct_v2_predictions_beam{num_beams}.csv"
    error_summary_csv_path = OUTPUT_DIR / f"pix2struct_v2_error_summary_beam{num_beams}.csv"

    result_summary = {
        "model_name": MODEL_NAME,
        "prompt": PROMPT,
        "version": "pix2struct_v2",
        "num_beams": num_beams,
        "max_samples": MAX_SAMPLES,
        "epochs_requested": EPOCHS,
        "best_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "early_stopping_patience": EARLY_STOPPING_PATIENCE,
        "batch_size": BATCH_SIZE,
        "accumulation_steps": ACCUMULATION_STEPS,
        "learning_rate": LEARNING_RATE,
        "gradient_clip_norm": GRAD_CLIP_NORM,
        "use_image_preprocessing": USE_IMAGE_PREPROCESSING,
        "use_train_augmentation": USE_TRAIN_AUGMENTATION,
        "resize_long_side": RESIZE_LONG_SIDE,
        "contrast_factor": CONTRAST_FACTOR,
        "sharpness_factor": SHARPNESS_FACTOR,
        "denoise_size": DENOISE_SIZE,
        "train_count": len(train_samples),
        "val_count": len(val_samples),
        "cer": cer,
        "allergy_keyword_precision": allergy_metrics["allergy_precision"],
        "allergy_keyword_recall": allergy_metrics["allergy_recall"],
        "allergy_keyword_f1": allergy_metrics["allergy_f1"],
        "true_positive": allergy_metrics["true_positive"],
        "false_positive": allergy_metrics["false_positive"],
        "false_negative": allergy_metrics["false_negative"],
        "allergy_keywords": ALLERGY_KEYWORDS,
        "train_history": train_history,
    }

    with open(result_json_path, "w", encoding="utf-8") as f:
        json.dump(result_summary, f, ensure_ascii=False, indent=2)

    rows = []
    with open(prediction_jsonl_path, "w", encoding="utf-8") as f:
        for filename, ref, pred, sample_cer, error_type in zip(
            filenames, references, predictions, sample_cers, error_types
        ):
            row = {
                "file_name": filename,
                "target": ref,
                "prediction": pred,
                "cer": sample_cer,
                "error_type": error_type,
                "reference_allergy_keywords": sorted(list(extract_allergy_keywords(ref))),
                "prediction_allergy_keywords": sorted(list(extract_allergy_keywords(pred))),
            }
            rows.append(row)
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    pred_df = pd.DataFrame(rows)
    pred_df.to_csv(prediction_csv_path, index=False, encoding="utf-8-sig")

    error_summary_df = (
        pred_df.groupby("error_type")
        .agg(count=("file_name", "count"), mean_cer=("cer", "mean"))
        .reset_index()
        .sort_values("count", ascending=False)
    )
    error_summary_df.to_csv(error_summary_csv_path, index=False, encoding="utf-8-sig")

    print("저장 완료:", result_json_path)
    print("예측 JSONL 저장:", prediction_jsonl_path)
    print("예측 CSV 저장:", prediction_csv_path)
    print("오류 요약 CSV 저장:", error_summary_csv_path)

zip_file = shutil.make_archive("/content/pix2struct_food_v2_result", "zip", OUTPUT_DIR)
print("Best model:", BEST_MODEL_DIR)
print("Final model:", FINAL_MODEL_DIR)
print("Zipped output:", zip_file)